continue=true
max-concurrent-downloads=1
split=16
max-connection-per-server=16
min-split-size=4M
max-overall-download-limit=0
max-download-limit=0
retry-wait=5
max-tries=20
timeout=60
file-allocation=trunc
allow-overwrite=true
auto-file-renaming=false
enable-http-pipelining=false
http-accept-gzip=true
check-certificate=true
enable-mmap=true
socket-recv-buffer-size=0
summary-interval=1
show-console-readout=true
truncate-console-readout=false
console-log-level=warn
follow-torrent=false
follow-metalink=false